### ISSUE TITLE
Failing tests in `internal/jj/` and `cmd/`

### ISSUE THREAD

**Issue by Adda0** [idursun/jjui#3]
Hello. Thanks for a great TUI tool. I [packaged `jjui` for Nix](https://github.com/NixOS/nixpkgs/pull/363738). However, running tests for the package fails with the following issues:

1. panic on index out of range in `cd internal/jj && go test`, and
2. generated output differs from the expected output in `cd cmd && go test`.

Tests for other subpackages seems to work.

<details><summary>Build output with failed tests</summary>
<p>

1. After running `cd internal/jj && go test`:

```
--- FAIL: Test_parseLogOutput_RootCommit (0.00s)
panic: runtime error: index out of range [10] with length 10 [recovered]
        panic: runtime error: index out of range [10] with length 10

goroutine 8 [running]:
testing.tRunner.func1.2({0x5f2760, 0xc00001e498})
        /nix/store/zhq8dnjbhwspzdglyq28j74axvqyk86q-go-1.23.3/share/go/src/testing/testing.go:1632 +0x230
testing.tRunner.func1()
        /nix/store/zhq8dnjbhwspzdglyq28j74axvqyk86q-go-1.23.3/share/go/src/testing/testing.go:1635 +0x35e
panic({0x5f2760?, 0xc00001e498?})
        /nix/store/zhq8dnjbhwspzdglyq28j74axvqyk86q-go-1.23.3/share/go/src/runtime/panic.go:785 +0x132
jjui/internal/jj.parseCommit({0xc0000d0210, 0xa, 0x78d120?})
        /home/adda/documents/it/jjui/internal/jj/jj.go:104 +0x4d7
jjui/internal/jj.parseLogOutput({0x615c44?, 0x605?})
        /home/adda/documents/it/jjui/internal/jj/jj.go:77 +0x1d3
jjui/internal/jj.Test_parseLogOutput_RootCommit(0xc0000deb60)
        /home/adda/documents/it/jjui/internal/jj/jj_test.go:41 +0x28
testing.tRunner(0xc0000deb60, 0x631840)
        /nix/store/zhq8dnjbhwspzdglyq28j74axvqyk86q-go-1.23.3/share/go/src/testing/testing.go:1690 +0xf4
created by testing.(*T).Run in goroutine 1
        /nix/store/zhq8dnjbhwspzdglyq28j74axvqyk86q-go-1.23.3/share/go/src/testing/testing.go:1743 +0x390
exit status 2
FAIL    jjui/internal/jj        0.006s
```

3. After running `cd cmd && go test`:
```
--- FAIL: TestRender_Single (0.00s)
    jjui_test.go:154:
                Error Trace:    /home/adda/documents/it/jjui/cmd/jjui_test.go:154
                                                        /home/adda/documents/it/jjui/cmd/jjui_test.go:32
                Error:          Not equal:
                                expected: "○ topchange\n│ (no description set)"
                                actual  : "\x1b[31m○\x1b[0m \x1b[1;34m\x1b[0m\x1b[90mtopchange\x1b[0m \x1b[33m\x1b[0m \x1b[36m\x1b[0m \x1b[34m\x1b[0m\n│ \x1b[1;33m(no description set)\x1b[0m"

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1,2 +1,2 @@
                                -○ topchange
                                -│ (no description set)
                                +○ topchange
                                +│ (no description set)
                Test:           TestRender_Single
--- FAIL: TestRender_ElidedRevisions (0.00s)
    jjui_test.go:154:
                Error Trace:    /home/adda/documents/it/jjui/cmd/jjui_test.go:154
                                                        /home/adda/documents/it/jjui/cmd/jjui_test.go:59
                Error:          Not equal:
                                expected: "○ a\n│ (no description set)\n~ (elided revisions)\n○ b\n│ (no description set)"
                                actual  : "\x1b[31m○\x1b[0m \x1b[1;34m\x1b[0m\x1b[90ma\x1b[0m \x1b[33m\x1b[0m \x1b[36m\x1b[0m \x1b[34m\x1b[0m\n│ \x1b[1;33m(no description set)\x1b[0m\n\x1b[90m~ (elided revisions)\x1b[0m\n○ \x1b[1;34m\x1b[0m\x1b[90mb\x1b[0m \x1b[33m\x1b[0m \x1b[36m\x1b[0m \x1b[34m\x1b[0m\n│ \x1b[1;33m(no description set)\x1b[0m"

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1,5 +1,5 @@
                                -○ a
                                -│ (no description set)
                                -~ (elided revisions)
                                -○ b
                                -│ (no description set)
                                +○ a
                                +│ (no description set)
                                +~ (elided revisions)
                                +○ b
                                +│ (no description set)
                Test:           TestRender_ElidedRevisions
--- FAIL: TestRender_Branched (0.00s)
    jjui_test.go:154:
                Error Trace:    /home/adda/documents/it/jjui/cmd/jjui_test.go:154
                                                        /home/adda/documents/it/jjui/cmd/jjui_test.go:88
                Error:          Not equal:
                                expected: "○ a1\n│ (no description set)\n│ ○ b\n├─╯ (no description set)\n○ root\n│ (no description set)"
                                actual  : "\x1b[31m○\x1b[0m \x1b[1;34m\x1b[0m\x1b[90ma1\x1b[0m \x1b[33m\x1b[0m \x1b[36m\x1b[0m \x1b[34m\x1b[0m\n│ \x1b[1;33m(no description set)\x1b[0m\n│ ○ \x1b[1;34m\x1b[0m\x1b[90mb\x1b[0m \x1b[33m\x1b[0m \x1b[36m\x1b[0m \x1b[34m\x1b[0m\n├─╯ \x1b[1;33m(no description set)\x1b[0m\n○ \x1b[1;34m\x1b[0m\x1b[90mroot\x1b[0m \x1b[33m\x1b[0m \x1b[36m\x1b[0m \x1b[34m\x1b[0m\n│ \x1b[1;33m(no description set)\x1b[0m"

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1,6 +1,6 @@
                                -○ a1
                                -│ (no description set)
                                -│ ○ b
                                -├─╯ (no description set)
                                -○ root
                                -│ (no description set)
                                +○ a1
                                +│ (no description set)
                                +│ ○ b
                                +├─╯ (no description set)
                                +○ root
                                +│ (no description set)
                Test:           TestRender_Branched
--- FAIL: TestRender_BranchedOrdered (0.00s)
    jjui_test.go:154:
                Error Trace:    /home/adda/documents/it/jjui/cmd/jjui_test.go:154
                                                        /home/adda/documents/it/jjui/cmd/jjui_test.go:148
                Error:          Not equal:
                                expected: "○ wzpt\n│ (no description set)\n○ xumz\n│ (no description set)\n~ (elided revisions)\n│ ○ tnww\n├─╯ (no description set)\n│ ○ rnym\n├─╯ (no description set)\n○ uolv\n│ (no description set)"
                                actual  : "\x1b[31m○\x1b[0m \x1b[1;34m\x1b[0m\x1b[90mwzpt\x1b[0m \x1b[33m\x1b[0m \x1b[36m\x1b[0m \x1b[34m\x1b[0m\n│ \x1b[1;33m(no description set)\x1b[0m\n○ \x1b[1;34m\x1b[0m\x1b[90mxumz\x1b[0m \x1b[33m\x1b[0m \x1b[36m\x1b[0m \x1b[34m\x1b[0m\n│ \x1b[1;33m(no description set)\x1b[0m\n\x1b[90m~ (elided revisions)\x1b[0m\n│ ○ \x1b[1;34m\x1b[0m\x1b[90mtnww\x1b[0m \x1b[33m\x1b[0m \x1b[36m\x1b[0m \x1b[34m\x1b[0m\n├─╯ \x1b[1;33m(no description set)\x1b[0m\n│ ○ \x1b[1;34m\x1b[0m\x1b[90mrnym\x1b[0m \x1b[33m\x1b[0m \x1b[36m\x1b[0m \x1b[34m\x1b[0m\n├─╯ \x1b[1;33m(no description set)\x1b[0m\n○ \x1b[1;34m\x1b[0m\x1b[90muolv\x1b[0m \x1b[33m\x1b[0m \x1b[36m\x1b[0m \x1b[34m\x1b[0m\n│ \x1b[1;33m(no description set)\x1b[0m"

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1,11 +1,11 @@
                                -○ wzpt
                                -│ (no description set)
                                -○ xumz
                                -│ (no description set)
                                -~ (elided revisions)
                                -│ ○ tnww
                                -├─╯ (no description set)
                                -│ ○ rnym
                                -├─╯ (no description set)
                                -○ uolv
                                -│ (no description set)
                                +○ wzpt
                                +│ (no description set)
                                +○ xumz
                                +│ (no description set)
                                +~ (elided revisions)
                                +│ ○ tnww
                                +├─╯ (no description set)
                                +│ ○ rnym
                                +├─╯ (no description set)
                                +○ uolv
                                +│ (no description set)
                Test:           TestRender_BranchedOrdered
FAIL
exit status 1
FAIL    jjui/cmd        0.003s
```

Here, it seems that the output is correct, but the expected output does not consider the colours in the generated output. 

</p>
</details>

**Comment by idursun** [comment]
Hey, thanks for working on this! 

Yes, I was aware that some tests were failing but didn't get around to fixing them as I am constantly changing the internals and didn't feel like updating them until I settle on a final approach that I am happy with.

However, I am a little puzzled by the failure of the `cmd` tests as they ran perfectly fine for me when I run them with `go test ./cmd`. I will keep this in mind. Anyhow, I removed the failing test files for the time being because they will be obsolete pretty very soon.

**Comment by Adda0** [comment]
Hey. Thank you. I expected this to be the case. I do not use Go so I cannot really help regarding the failures. This issue was just to let you know. Resolving the issues is by no means necessary for successful packaging of the tool. I should have specified that earlier. I will therefore re-enable the tests in my package again and will see how it goes now.

**Comment by Adda0** [comment]
Indeed, everything runs now as expected. The tests are now re-enabled in the package. But if you do not want to update and fix the tests all the time, feel free to let me know, and I can keep the tests disabled to not force you into fixing the tests until everything is more stable.

**Comment by idursun** [comment]
I better keep them passing at all time 😄  

Thank you very much for your efforts on the nix side.
